/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary': '#ffb3b3',
        'primary-container': '#dc143c',
        'primary-fixed': '#ffdad9',
        'primary-fixed-dim': '#ffb3b3',
        'on-primary': '#680015',
        'on-primary-container': '#fff1f0',
        'on-primary-fixed': '#40000a',
        'on-primary-fixed-variant': '#920022',
        'inverse-primary': '#bf0030',
        'secondary': '#f6be3b',
        'secondary-container': '#c69302',
        'secondary-fixed': '#ffdea0',
        'secondary-fixed-dim': '#f6be3b',
        'on-secondary': '#402d00',
        'on-secondary-container': '#433000',
        'on-secondary-fixed': '#261900',
        'on-secondary-fixed-variant': '#5c4300',
        'tertiary': '#ffb68c',
        'tertiary-container': '#a85b28',
        'tertiary-fixed': '#ffdbc9',
        'tertiary-fixed-dim': '#ffb68c',
        'on-tertiary': '#532200',
        'on-tertiary-container': '#fff1eb',
        'on-tertiary-fixed': '#321200',
        'on-tertiary-fixed-variant': '#753401',
        'surface': '#1b110d',
        'surface-dim': '#1b110d',
        'surface-bright': '#433731',
        'surface-variant': '#3e322d',
        'surface-container-lowest': '#150c08',
        'surface-container-low': '#231914',
        'surface-container': '#281d18',
        'surface-container-high': '#332822',
        'surface-container-highest': '#3e322d',
        'surface-tint': '#ffb3b3',
        'on-surface': '#f2dfd6',
        'on-surface-variant': '#e6bdbc',
        'inverse-surface': '#f2dfd6',
        'inverse-on-surface': '#392e28',
        'background': '#1b110d',
        'on-background': '#f2dfd6',
        'outline': '#ac8888',
        'outline-variant': '#5c3f3f',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'gutter': '24px',
        'container-max': '1200px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
        'base': '8px',
      },
      fontFamily: {
        headline: ['Playfair Display', 'serif'],
        'headline-lg': ['Playfair Display', 'serif'],
        'headline-md': ['Playfair Display', 'serif'],
        'display-lg': ['Playfair Display', 'serif'],
        'display-lg-mobile': ['Playfair Display', 'serif'],
        body: ['Noto Serif', 'serif'],
        'body-lg': ['Noto Serif', 'serif'],
        'body-md': ['Noto Serif', 'serif'],
        'label-lg': ['Noto Serif', 'serif'],
        'label-sm': ['Noto Serif', 'serif'],
      },
      fontSize: {
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.03em', fontWeight: '500' }],
      },
      maxWidth: { 'container-max': '1200px' },
    },
  },
  plugins: [],
}
